language: node_js
node_js:
  - "node"
services:
  - docker
script:
  - docker-compose run --rm --use-aliases app
deploy:
  provider: npm
  email: andrej@chocolatejar.eu
  api_key: $NPM_TOKEN
  on:
    tags: true
